# -*- coding: utf-8 -*-
"""DenseNet121_Baseline_NoFourier_FIXED_TEST_EVAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJDnVM2CVkIXO3-NkM794q-iw7Pb9g6_

# DenseNet121 Baseline No Fourier — FIXED Test Evaluation

Javított baseline test-evaluation notebook.

Fontos javítás:
- a modell classifier része pontosan ugyanaz, mint a tanításnál,
- checkpoint local `/content` alá másolva töltődik be,
- `strict=True`, hogy ne adjon hamis eredményt részleges betöltéssel.
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image
from tqdm.auto import tqdm

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from torchvision import models, transforms
from torchvision.transforms import InterpolationMode

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)
print("Torch:", torch.__version__)

# =========================
# PATHOK ÉS BEÁLLÍTÁSOK
# =========================

DENSENET_CKPT = "/content/drive/MyDrive/Brain MRI/FNO_clas/no fourier/best_densenet121_baseline.pth"

TEST_DIR = "/content/drive/MyDrive/Brain MRI/brisc2025/classification_task/test"

OUT_DIR = "/content/drive/MyDrive/Brain MRI/FNO_clas/no fourier/densenet121_test_evaluation_FIXED"
os.makedirs(OUT_DIR, exist_ok=True)

IMG_SIZE = 224
BATCH_SIZE = 8
NUM_WORKERS = 2

CLASS_NAMES = ["glioma", "meningioma", "no_tumor", "pituitary"]
label_map = {c: i for i, c in enumerate(CLASS_NAMES)}
label_map_inv = {i: c for c, i in label_map.items()}

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

print("Checkpoint exists:", os.path.exists(DENSENET_CKPT))
print("Test exists:", os.path.exists(TEST_DIR))
print("Output:", OUT_DIR)

if not os.path.exists(DENSENET_CKPT):
    raise FileNotFoundError(DENSENET_CKPT)

if not os.path.exists(TEST_DIR):
    raise FileNotFoundError(TEST_DIR)

# =========================
# TEST FÁJLOK BEOLVASÁSA
# =========================

def normalize_folder_name(name):
    s = name.lower().strip().replace("-", "_").replace(" ", "_")
    if "glioma" in s:
        return "glioma"
    if "meningioma" in s:
        return "meningioma"
    if "pituitary" in s:
        return "pituitary"
    if s in ["no_tumor", "notumor", "no_tumour", "notumour", "normal", "healthy"]:
        return "no_tumor"
    if "no" in s and ("tumor" in s or "tumour" in s):
        return "no_tumor"
    return s

valid_exts = (".png", ".jpg", ".jpeg", ".bmp", ".webp", ".tif", ".tiff")

rows = []

print("Test mappa tartalma:")
for folder in sorted(os.listdir(TEST_DIR)):
    folder_path = os.path.join(TEST_DIR, folder)
    if not os.path.isdir(folder_path):
        continue

    label = normalize_folder_name(folder)

    n_imgs = len([f for f in os.listdir(folder_path) if f.lower().endswith(valid_exts)])
    print(f"{folder:25s} -> {label:12s} -> {n_imgs} kép")

    if label not in label_map:
        print("Kihagyva:", folder)
        continue

    for fname in sorted(os.listdir(folder_path)):
        if fname.lower().endswith(valid_exts):
            rows.append({
                "image_path": os.path.join(folder_path, fname),
                "folder_label": folder,
                "label": label,
                "label_idx": label_map[label]
            })

df_test = pd.DataFrame(rows)

if len(df_test) == 0:
    raise RuntimeError("Nem találtam képeket a test mappában.")

print("\nÖsszes test kép:", len(df_test))
display(df_test["label"].value_counts().reindex(CLASS_NAMES).fillna(0).astype(int).to_frame("count"))

file_list_path = os.path.join(OUT_DIR, "test_file_list.csv")
df_test.to_csv(file_list_path, index=False)
print("Mentve:", file_list_path)

# =========================
# DATASET ÉS DATALOADER
# =========================

test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE), interpolation=InterpolationMode.BILINEAR),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
])

class BrainTumorDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.data = dataframe.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]
        image = Image.open(row["image_path"]).convert("RGB")
        label = int(row["label_idx"])

        if self.transform:
            image = self.transform(image)

        return image, label, row["image_path"]

test_dataset = BrainTumorDataset(df_test, transform=test_transform)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available()
)

print("Dataset:", len(test_dataset))
print("Batches:", len(test_loader))

# =========================
# MODELL: DenseNet121 baseline - JAVÍTOTT
# Pontosan mint a tanításnál:
# model.classifier = Sequential(Dropout(0.25), Linear(...))
# =========================

model = models.densenet121(weights=None)
in_features = model.classifier.in_features
model.classifier = nn.Sequential(
    nn.Dropout(0.25),
    nn.Linear(in_features, len(CLASS_NAMES))
)
model = model.to(device)

print(model.classifier)

# =========================
# CHECKPOINT BETÖLTÉS - JAVÍTOTT
# =========================
# Drive hiba ellen először local /content alá másoljuk.
# strict=True: ha nem pontos az architektúra, azonnal hibát dob.

LOCAL_CKPT = "/content/best_densenet121_baseline.pth"
shutil.copy2(DENSENET_CKPT, LOCAL_CKPT)

try:
    ckpt = torch.load(LOCAL_CKPT, map_location=device, weights_only=True)
except TypeError:
    ckpt = torch.load(LOCAL_CKPT, map_location=device)
except Exception:
    ckpt = torch.load(LOCAL_CKPT, map_location=device)

if isinstance(ckpt, dict) and "model_state_dict" in ckpt:
    state = ckpt["model_state_dict"]
elif isinstance(ckpt, dict) and "state_dict" in ckpt:
    state = ckpt["state_dict"]
else:
    state = ckpt

state = {k.replace("module.", ""): v for k, v in state.items()}

model.load_state_dict(state, strict=True)
model = model.to(device)
model.eval()

print("Checkpoint sikeresen betöltve strict=True módban.")
print("Local checkpoint:", LOCAL_CKPT)

# =========================
# TEST KIÉRTÉKELÉS
# =========================

y_true = []
y_pred = []
y_prob = []
paths = []

use_amp = torch.cuda.is_available()

with torch.no_grad():
    for images, labels, image_paths in tqdm(test_loader, desc="Testing"):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.amp.autocast("cuda", enabled=use_amp):
            outputs = model(images)

        probs = torch.softmax(outputs, dim=1)
        preds = torch.argmax(probs, dim=1)

        y_true.extend(labels.cpu().numpy().tolist())
        y_pred.extend(preds.cpu().numpy().tolist())
        y_prob.extend(probs.cpu().numpy().tolist())
        paths.extend(list(image_paths))

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_prob = np.array(y_prob)

print("Predikciók elkészültek.")
print("y_true:", y_true.shape)
print("y_pred:", y_pred.shape)
print("y_prob:", y_prob.shape)

# =========================
# SUMMARY METRICS
# =========================

acc = accuracy_score(y_true, y_pred)

summary_df = pd.DataFrame([{
    "Model": "DenseNet121 Baseline No Fourier",
    "Test Accuracy": acc,
    "Macro Precision": precision_score(y_true, y_pred, average="macro", zero_division=0),
    "Macro Recall": recall_score(y_true, y_pred, average="macro", zero_division=0),
    "Macro F1-score": f1_score(y_true, y_pred, average="macro", zero_division=0),
    "Weighted Precision": precision_score(y_true, y_pred, average="weighted", zero_division=0),
    "Weighted Recall": recall_score(y_true, y_pred, average="weighted", zero_division=0),
    "Weighted F1-score": f1_score(y_true, y_pred, average="weighted", zero_division=0),
    "Number of test images": len(y_true)
}])

display(summary_df)

summary_path = os.path.join(OUT_DIR, "test_summary_metrics.csv")
summary_df.to_csv(summary_path, index=False)
print("Mentve:", summary_path)

# =========================
# CLASSIFICATION REPORT
# =========================

report_df = pd.DataFrame(
    classification_report(
        y_true,
        y_pred,
        labels=list(range(len(CLASS_NAMES))),
        target_names=CLASS_NAMES,
        output_dict=True,
        zero_division=0
    )
).transpose()

display(report_df)

report_path = os.path.join(OUT_DIR, "classification_report.csv")
report_df.to_csv(report_path)
print("Mentve:", report_path)

# =========================
# PAPER-READY METRIKA TÁBLÁZAT
# =========================

prec, rec, f1, support = precision_recall_fscore_support(
    y_true,
    y_pred,
    labels=list(range(len(CLASS_NAMES))),
    zero_division=0
)

rows = []

for i, cls in enumerate(CLASS_NAMES):
    rows.append({
        "Model": "DenseNet121 Baseline No Fourier",
        "Class": cls,
        "Precision": round(float(prec[i]), 4),
        "Recall": round(float(rec[i]), 4),
        "F1-Score": round(float(f1[i]), 4),
        "Support": int(support[i]),
        "Accuracy": ""
    })

rows.append({
    "Model": "",
    "Class": "Macro Avg",
    "Precision": round(float(precision_score(y_true, y_pred, average="macro", zero_division=0)), 4),
    "Recall": round(float(recall_score(y_true, y_pred, average="macro", zero_division=0)), 4),
    "F1-Score": round(float(f1_score(y_true, y_pred, average="macro", zero_division=0)), 4),
    "Support": int(np.sum(support)),
    "Accuracy": ""
})

rows.append({
    "Model": "",
    "Class": "Weighted Avg",
    "Precision": round(float(precision_score(y_true, y_pred, average="weighted", zero_division=0)), 4),
    "Recall": round(float(recall_score(y_true, y_pred, average="weighted", zero_division=0)), 4),
    "F1-Score": round(float(f1_score(y_true, y_pred, average="weighted", zero_division=0)), 4),
    "Support": int(np.sum(support)),
    "Accuracy": round(float(acc), 4)
})

results_table_df = pd.DataFrame(rows)
display(results_table_df)

results_path = os.path.join(OUT_DIR, "test_results_table.csv")
results_table_df.to_csv(results_path, index=False)
print("Mentve:", results_path)

# =========================
# CONFUSION MATRIX
# =========================

cm = confusion_matrix(y_true, y_pred, labels=list(range(len(CLASS_NAMES))))

cm_df = pd.DataFrame(
    cm,
    index=[f"True: {c}" for c in CLASS_NAMES],
    columns=[f"Pred: {c}" for c in CLASS_NAMES]
)

display(cm_df)

cm_csv = os.path.join(OUT_DIR, "confusion_matrix_counts.csv")
cm_df.to_csv(cm_csv)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_df, annot=True, fmt="d", cmap="Blues", cbar=True)
plt.title("Confusion Matrix")
plt.ylabel("True label")
plt.xlabel("Predicted label")
plt.xticks(rotation=35, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()

cm_png = os.path.join(OUT_DIR, "confusion_matrix.png")
plt.savefig(cm_png, dpi=300, bbox_inches="tight")
plt.show()

print("CSV:", cm_csv)
print("PNG:", cm_png)

# =========================
# NORMALIZED CONFUSION MATRIX
# =========================

row_sums = cm.sum(axis=1, keepdims=True)
cm_norm = np.divide(cm, row_sums, out=np.zeros_like(cm, dtype=float), where=row_sums != 0)

cm_norm_df = pd.DataFrame(
    cm_norm,
    index=[f"True: {c}" for c in CLASS_NAMES],
    columns=[f"Pred: {c}" for c in CLASS_NAMES]
)

display(cm_norm_df)

cm_norm_csv = os.path.join(OUT_DIR, "confusion_matrix_normalized.csv")
cm_norm_df.to_csv(cm_norm_csv)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_norm_df, annot=True, fmt=".2f", cmap="Blues", cbar=True, vmin=0, vmax=1)
plt.title("Normalized Confusion Matrix")
plt.ylabel("True label")
plt.xlabel("Predicted label")
plt.xticks(rotation=35, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()

cm_norm_png = os.path.join(OUT_DIR, "normalized_confusion_matrix.png")
plt.savefig(cm_norm_png, dpi=300, bbox_inches="tight")
plt.show()

print("CSV:", cm_norm_csv)
print("PNG:", cm_norm_png)

# =========================
# PER-IMAGE PREDICTIONS + MISCLASSIFIED
# =========================

pred_rows = []

for i in range(len(y_true)):
    row = {
        "image_path": paths[i],
        "true_idx": int(y_true[i]),
        "pred_idx": int(y_pred[i]),
        "true_label": label_map_inv[int(y_true[i])],
        "predicted_label": label_map_inv[int(y_pred[i])],
        "correct": bool(y_true[i] == y_pred[i]),
        "confidence": float(np.max(y_prob[i]))
    }

    for j, cname in enumerate(CLASS_NAMES):
        row[f"prob_{cname}"] = float(y_prob[i][j])

    pred_rows.append(row)

pred_df = pd.DataFrame(pred_rows)
display(pred_df.head(20))

pred_path = os.path.join(OUT_DIR, "per_image_predictions.csv")
pred_df.to_csv(pred_path, index=False)
print("Mentve:", pred_path)

wrong_df = pred_df[pred_df["correct"] == False].copy()
wrong_df = wrong_df.sort_values("confidence", ascending=False)

display(wrong_df.head(50))

wrong_path = os.path.join(OUT_DIR, "misclassified.csv")
wrong_df.to_csv(wrong_path, index=False)
print("Mentve:", wrong_path)

# =========================
# MISCLASSIFIED EXAMPLES
# =========================

def show_misclassified_examples(wrong_df, max_images=12):
    if len(wrong_df) == 0:
        print("Nincs hibás klasszifikáció.")
        return

    sample_df = wrong_df.head(max_images)
    n = len(sample_df)
    cols = 4
    rows = int(np.ceil(n / cols))

    plt.figure(figsize=(4 * cols, 4 * rows))

    for i, (_, row) in enumerate(sample_df.iterrows()):
        img = Image.open(row["image_path"]).convert("RGB")
        plt.subplot(rows, cols, i + 1)
        plt.imshow(img)
        plt.axis("off")
        plt.title(
            f"True: {row['true_label']}\nPred: {row['predicted_label']}\nConf: {row['confidence']:.2f}",
            fontsize=10
        )

    plt.tight_layout()
    out_path = os.path.join(OUT_DIR, "misclassified_examples.png")
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.show()
    print("Mentve:", out_path)

show_misclassified_examples(wrong_df)

print("Kész.")
print("Eredmények:", OUT_DIR)
print("\nFájlok:")
for f in sorted(os.listdir(OUT_DIR)):
    print("-", f)